- hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Create a Resource Group
      azure_rm_resourcegroup:
        name: ansiblerg
        location: eastus
        
    - name: Create a Storage Account
      azure_rm_storageaccount:
        resource_group: ansiblerg
        location: eastus
        name: successb876
        kind: StorageV2
        access_tier: Hot
        account_type: Standard_LRS
