- hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars_prompt:
    - name: RGName
    - name: location
    - name: strname
  tasks:
    - name: Create a Resource Group
      azure_rm_resourcegroup:
        name: "{{ RGName }}"
        location: "{{ location }}"
        
    - name: Create a Storage Account
      azure_rm_storageaccount:
        resource_group: "{{ RGName }}"
        location: "{{ location }}"
        name: "{{ strname }}"
        kind: StorageV2
        access_tier: Hot
        account_type: Standard_LRS

#ansible-playbook storage.yml --extra-vars "RGName=${RGName} location=${location} strname=${strname}"
